"""Shadow-run the FTMO bot (the same ``ftmo_bot.Runner`` the MT5 bot runs,
with no shadow-specific hooks) on a simulated
CAD 15,000 FTMO account, fed with live Astral 30-minute bars of the ETF
proxies (QQQ = US100, SPY = US500, DIA = US30, IWM = US2000).

    python scripts/ftmo_shadow.py --bars-dir DIR [--dir research/ftmo_shadow]
                                  [--start ISO] [--until ISO]

DIR holds ``qqq_30m.csv``, ``spy_30m.csv``, ``dia_30m.csv``, ``iwm_30m.csv``
(Astral exports). Each run continues from the saved state and ticks the
bot every 30 minutes of each US session (09:35 ... 16:05 New York), as a
bot polling the terminal would, never past the last bar every symbol
has (no look-ahead, no skipped stops). The journal records the FTMO
scorecard after each session; "lowest equity" includes open positions
marked at each bar's low.

Known differences from the live bot: it polls every 30 minutes, not
every minute, so the first entry chance is 10:05 at the 09:30 bar's
close (the live bot buys at about 09:31); ETF proxies stand in for the
CFDs (no FX, no swap, no CFD spread or contract sizes).
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, time, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ftmo_bot.broker_sim import BAR, SimBroker, load_csv, save_json  # noqa: E402
from ftmo_bot.config import FtmoConfig  # noqa: E402
from ftmo_bot.runner import Runner  # noqa: E402

NY = ZoneInfo("America/New_York")
PROXIES = {"US100": "QQQ", "US500": "SPY", "US30": "DIA", "US2000": "IWM"}
INITIAL = 15000.0
log = logging.getLogger("ftmo_bot")


def tick_times(after: datetime, until: datetime):
    d = after.astimezone(NY).date()
    while d <= until.astimezone(NY).date():
        if d.weekday() < 5:
            t = datetime.combine(d, time(9, 35), NY)
            while t.time() <= time(16, 5):
                if after < t <= until:
                    yield t
                t += timedelta(minutes=30)
        d += timedelta(days=1)


def journal(path: Path, days: list) -> None:
    rows = ["# FTMO bot shadow run (simulated CAD 15,000, 3% risk)", "",
            "Generated by `scripts/ftmo_shadow.py`; the bot code is "
            "the same `ftmo_bot.Runner` the MT5 bot runs (no shadow hooks). "
            "ETF proxies, no FX, no swap.", "",
            "| session | balance | equity | P&L vs start | lowest equity | "
            "daily floor | max-loss floor | open | next-open plan | deals | "
            "trading days | flags |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in days:
        rows.append(
            f"| {r['day']} | {r['balance']:,.2f} | {r['equity']:,.2f} | "
            f"{r['equity'] / INITIAL - 1:+.2%} | {r['min_equity']:,.2f} | "
            f"{r['daily_floor']:,.2f} | {INITIAL * 0.9:,.2f} | "
            f"{', '.join(r['open']) or '-'} | {r['plan'] or '-'} | "
            f"{'; '.join(r['deals']) or '-'} | {r['trading_days']} | "
            f"{', '.join(r['flags']) or 'ok'} |")
    path.write_text("\n".join(rows) + "\n")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bars-dir", required=True, type=Path)
    ap.add_argument("--dir", default="research/ftmo_shadow", type=Path)
    ap.add_argument("--start", help="ISO start time (first run only)")
    ap.add_argument("--until", help="ISO end time (default: now)")
    a = ap.parse_args(argv)
    a.dir.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(level=logging.INFO, format="%(message)s",
                        handlers=[logging.FileHandler(a.dir / "bot.log")])
    fmt = logging.Formatter("%(levelname)s %(message)s")
    for h in logging.getLogger().handlers:
        h.setFormatter(fmt)

    bars = {p: load_csv(a.bars_dir / f"{p.lower()}_30m.csv") for p in PROXIES.values()}
    sim_path, days_path = a.dir / "sim.json", a.dir / "days.json"
    state = json.loads(sim_path.read_text()) if sim_path.exists() else None
    sim = SimBroker(bars, state, balance=INITIAL)
    if sim.clock is None:
        if not a.start:
            ap.error("--start is required on the first run")
        sim.clock = datetime.fromisoformat(a.start).astimezone(timezone.utc)
    days = json.loads(days_path.read_text()) if days_path.exists() else []
    run_path = a.dir / "run.json"           # running per-day stats across runs
    run = (json.loads(run_path.read_text()) if run_path.exists()
           else {"day_min": {}, "deals_logged": 0, "errors": 0})

    def persist() -> None:
        save_json(sim_path, sim.state())
        save_json(run_path, run)
        days_path.write_text(json.dumps(days, indent=2))

    cfg = FtmoConfig(symbols=dict(PROXIES), dry_run=False, initial_balance=INITIAL,
                     state_path=str(a.dir / "bot_state.json"),
                     log_path=str(a.dir / "bot.log"))
    cfg.validate()
    r = Runner(cfg, sim)

    until = (datetime.fromisoformat(a.until) if a.until
             else datetime.now(timezone.utc)).astimezone(timezone.utc)
    have = min(bs[-1][0] + BAR for bs in bars.values())   # every symbol has data
    until = min(until, have + timedelta(minutes=6))
    errors, day_min = 0, run["day_min"]
    for t in tick_times(sim.clock, until):
        prev = sim.clock
        sim.advance_to(t)
        d = t.astimezone(NY).date().isoformat()
        try:
            low = sim.low_equity(prev)           # open positions at their bar lows
            r.tick(t)
            eq = sim.account().equity
        except Exception:
            errors += 1
            run["errors"] += 1
            log.exception("tick %s failed", t)
            persist()
            continue
        day_min[d] = min(day_min.get(d, eq), eq, low)
        if t.astimezone(NY).time() == time(16, 5):
            new = sim.deals[run["deals_logged"]:]
            run["deals_logged"] = len(sim.deals)
            st = r.st
            flags = []
            if st.halted:
                flags.append(f"HALTED: {st.halted}")
            if st.blocked_until:
                flags.append(f"entries blocked until {st.blocked_until}")
            floor = (st.day_start_balance or INITIAL) - 0.05 * INITIAL
            if day_min[d] <= floor:
                flags.append("DAILY LIMIT BREACHED")
            if day_min[d] <= INITIAL * 0.9:
                flags.append("MAX LOSS BREACHED")
            plan = " ".join([f"exit {s}" for s in st.pending_exits]
                            + [f"buy {s}" for s in st.pending_entries])
            days = [x for x in days if x["day"] != d] + [{
                "day": d, "balance": sim.balance, "equity": eq,
                "min_equity": day_min[d], "daily_floor": floor,
                "open": [f"{p.symbol} {p.volume:.2f}@{p.price_open:.2f} sl {p.sl:.2f}"
                         for p in sim.pos],
                "plan": plan,
                "deals": [f"{x['side']} {x['symbol']} {x['volume']:.2f}@{x['price']}"
                          + (f" {x['pnl']:+.2f} ({x['why']})" if "pnl" in x else "")
                          for x in new],
                "trading_days": len(st.trading_days), "flags": flags,
                "errors": run["errors"]}]
        persist()
    if until > sim.clock:
        sim.advance_to(until)
    persist()
    journal(a.dir / "JOURNAL.md", days)
    last = days[-1] if days else None
    print(f"shadow clock {sim.clock.astimezone(NY):%Y-%m-%d %H:%M} NY, "
          f"balance {sim.balance:,.2f}, open {[p.symbol for p in sim.pos]}, "
          f"tick errors {errors}")
    if last:
        print(f"last session {last['day']}: equity {last['equity']:,.2f}, "
              f"plan '{last['plan']}', flags {last['flags'] or 'ok'}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
